#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

development:
  adapter: postgresql
  database: pins_development
  host: localhost


#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000

test:
  adapter: postgresql
  database: pins_development
  database: ping_test
  host: localhost

Production:
  adapter: postgresql
  database: pins_development
